### PR TITLE
Issues/87 :: Wrong / Mixed information on challenges page and teaser

### PR DESCRIPTION
**Pull request by AndrewDrupal**
#87

### CODE REVIEW

**Comment by zohar** [comment]
@AndrewDrupal It seems to me that you did the inverse of what I requested. On my local environment, all the challenges show only the moderator, while they should display the author. (see attached images)

the second challenge openideal - ideas and innovation management system

edit challenge the first challenge openideal - ideas and innovation management system

**Comment by AndrewDrupal** [comment]
@zohar 
At our stand shows author of the challenge. - https://www.screencast.com/t/EuebNvUth 
Please recheck.

There is another reference problem: the moderator’s name and avatar is displayed on the "Challenges" page. But this is not the problem of the current task.

**Comment by zohar** [comment]
@AndrewDrupal - the end result should be: in Challenges, show the author name and picture, in all places where the challenge is displayed. 

The moderator field should be completely removed as soon as we're sure it is not used elsewhere.

**Comment by AndrewDrupal** [comment]
@zohar 
Done.

**Comment by zohar** [comment]
@AndrewDrupal 
**Looks good** but I still have issues with the page "/challenges" where all the nodes have the same author.

Please make sure the author is displayed - throughout the site - wherever a challenge is displayed.

**Comment by AndrewDrupal** [comment]
Also change moderator to author on front page.

**Pull request merged**
